# Generated by Django 4.2.9 on 2024-02-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("context", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="use_openai",
            field=models.BooleanField(default=True),
        ),
    ]
