# Generated by Django 4.2.9 on 2024-02-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("context", "0003_collection_use_openai"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="content_hash",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
