# Generated by Django 5.0.4 on 2024-04-23 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("context", "0004_document_content_hash"),
        ("crawler", "0009_crawlconfig_include_paths"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crawler.page",
            ),
        ),
    ]
