# Generated by Django 5.0.4 on 2024-05-22 11:56

import context.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0005_alter_document_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(upload_to=context.models.get_upload_name)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context.collection')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='context.file'),
        ),
    ]
