# Generated by Django 5.1.1 on 2025-02-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("context", "0008_collection_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="require_auth",
            field=models.BooleanField(default=False),
        ),
    ]
