# Generated by Django 4.2.9 on 2024-01-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('system_prompt_template', models.TextField(blank=True)),
                ('user_prompt_template', models.TextField(blank=True)),
                ('model_max_length', models.IntegerField()),
                ('output_max_length', models.IntegerField()),
                ('is_public', models.BooleanField()),
            ],
        ),
    ]
