# Generated by Django 5.0.6 on 2024-06-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbot",
            name="base_url",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
