# Generated by Django 5.0.7 on 2024-08-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatbot_functions'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tools',
            field=models.JSONField(default=dict),
        ),
    ]
