# Generated by Django 5.0.6 on 2024-09-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_message_tools"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbot",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
