# Generated by Django 4.2.9 on 2024-01-31 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('context', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2000, unique=True)),
                ('domain', models.CharField(max_length=500)),
                ('last_fetched', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrawlConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100)),
                ('start_url', models.CharField(max_length=500)),
                ('allowed_domains', models.TextField(blank=True)),
                ('last_fetched', models.DateTimeField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('target_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context.collection')),
            ],
        ),
    ]
