# Generated by Django 4.2.9 on 2024-02-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0003_alter_crawlconfig_last_fetched"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="error",
            field=models.TextField(blank=True),
        ),
    ]
