# Generated by Django 4.2.9 on 2024-02-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0006_crawlconfig_arguments"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="page",
            index=models.Index(
                fields=["url", "domain"], name="crawler_pag_url_243307_idx"
            ),
        ),
    ]
