# Generated by Django 5.0.4 on 2024-05-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0009_crawlconfig_include_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='stale',
            field=models.BooleanField(default=False),
        ),
    ]
