# Generated by Django 5.0.6 on 2024-07-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0010_page_stale"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawlconfig",
            name="timeout",
            field=models.FloatField(default=0.0),
        ),
    ]
