# Generated by Django 5.0.6 on 2024-09-13 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0012_crawlconfig_stale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlconfig',
            name='stale',
        ),
    ]
