# Generated by Django 5.1.1 on 2024-10-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0013_remove_crawlconfig_stale"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
